name: Dashboard Mannually Package
on: workflow_dispatch
jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: reg.vesoft-inc.com/dashboard/dashboard-dev:${{ matrix.os }}
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          path: source/nebula-graph-dashboard
=======
      - name: keep workspace empty
        run: |
          rm -rf *
      - uses: actions/checkout@v2
        with:
          path: source/nebula-dashboard
>>>>>>> 26d54c1 (fix: gateway disconnect issue (#52))
      - uses: actions/checkout@v2
        with:
          repository: vesoft-inc/nebula-http-gateway
          path: source/nebula-http-gateway
<<<<<<< HEAD
      ##ToDO: add nebula-stats-exporterã€node-exporter and prometheus 
=======
          ref: v2.2.1
>>>>>>> 26d54c1 (fix: gateway disconnect issue (#52))
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: ls
        run: ls -a
      - name: Package
        run: bash ./source/nebula-graph-dashboard/scripts/package.sh ${{ secrets.GA_ID }}
      - name: Upload to OSS
<<<<<<< HEAD
        run: ls -a & ossutil64 -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ID }} -k ${{ secrets.OSS_SECRET }} -f cp ./  ${{ secrets.OSS_TEST_URL }} --include "nebula-graph-dashboard-*.tar.gz" --only-current-dir -r
=======
        run: bash ./source/nebula-dashboard/scripts/upload.sh ${{ secrets.OSS_ENDPOINT }} ${{ secrets.OSS_ID }} ${{ secrets.OSS_SECRET }} ${{ secrets.OSS_URL }}
>>>>>>> 26d54c1 (fix: gateway disconnect issue (#52))

    
