name: Dashboard tar Release
on:
<<<<<<< HEAD
  release:
    types:
      - published
=======
  push:
    branches:
      - nico-dev
>>>>>>> 8b2e53a (mod: fix issue & chore nebula-stats-exporter (#55))
jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
<<<<<<< HEAD
          ref: 'master'
=======
          ref: 'nico-dev'
>>>>>>> 8b2e53a (mod: fix issue & chore nebula-stats-exporter (#55))
          path: source/nebula-graph-dashboard
      - uses: actions/checkout@v2
        with:
          repository: vesoft-inc/nebula-http-gateway
          path: source/nebula-http-gateway
<<<<<<< HEAD
      ##ToDO: add nebula-stats-exporterã€node-exporter and prometheus 
=======
>>>>>>> 8b2e53a (mod: fix issue & chore nebula-stats-exporter (#55))
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: ls
        run: ls -a
      - name: Package
<<<<<<< HEAD
        run: bash ./source/nebula-graph-dashboard/scripts/package.sh ${{ secrets.GA_ID }}
      - name: Upload to OSS
        run: bash ./source/nebula-graph-dashboard/scripts/upload.sh ${{ secrets.OSS_ENDPOINT }} ${{ secrets.OSS_ID }} ${{ secrets.OSS_SECRET }} ${{ secrets.OSS_URL }}
=======
        run: bash ./source/nebula-graph-dashboard/scripts/package.sh
      - name: Upload to OSS
        run: ls -a & ossutil64 -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ID }} -k ${{ secrets.OSS_SECRET }} -f cp ./  ${{ secrets.OSS_URL }} --include "nebula-graph-dashboard-beta.tar.gz" --only-current-dir -r
>>>>>>> 8b2e53a (mod: fix issue & chore nebula-stats-exporter (#55))

    
