name: Dashboard tar Release
on:
  release:
    types:
      - published
jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: reg.vesoft-inc.com/dashboard/dashboard-dev:${{ matrix.os }}
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
<<<<<<< HEAD
=======
      - name: keep workspace empty
        run: |
          rm -rf *
>>>>>>> 977ecb6 (fix: gateway disconnect issue (#51))
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          path: source/nebula-graph-dashboard
      - uses: actions/checkout@v2
        with:
          repository: vesoft-inc/nebula-http-gateway
          path: source/nebula-http-gateway
<<<<<<< HEAD
      ##ToDO: add nebula-stats-exporterã€node-exporter and prometheus 
=======
          ref: v2.2.1
>>>>>>> 977ecb6 (fix: gateway disconnect issue (#51))
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: ls
        run: ls -a
      - name: Package
        run: bash ./source/nebula-graph-dashboard/scripts/package.sh ${{ secrets.GA_ID }}
      - name: Upload to OSS
        run: bash ./source/nebula-graph-dashboard/scripts/upload.sh ${{ secrets.OSS_ENDPOINT }} ${{ secrets.OSS_ID }} ${{ secrets.OSS_SECRET }} ${{ secrets.OSS_URL }}

    
