name: Dashboard tar Release
on:
  release:
    types:
      - published
jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - name: keep workspace empty
        run: |
          rm -rf *
      - uses: actions/checkout@v2
        with:
          path: source/nebula-dashboard
      - uses: actions/checkout@v2
        with:
          repository: vesoft-inc/nebula-http-gateway
          path: source/nebula-http-gateway
          ref: v3.1.4
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: ls
        run: ls -a
      - name: Package
        run: |
          DIR=`pwd`
          bash ./source/nebula-dashboard/scripts/package.sh ./source/nebula-dashboard /source/nebula-http-gateway $DIR/source/nebula-dashboard $DIR/source/nebula-http-gateway false ${{ secrets.GA_ID }} 
      - name: Upload to OSS
        run: bash ./source/nebula-dashboard/scripts/upload.sh ${{ secrets.OSS_ENDPOINT }} ${{ secrets.OSS_ID }} ${{ secrets.OSS_SECRET }} ${{ secrets.OSS_URL }}

    
